name: eiqro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_radar_chart: ^0.2.0
  get: ^4.6.1
  get_storage: 2.0.3
  http: ^0.13.4
  intl: 0.17.0
  provider: ^6.0.2
  supercharged: ^2.1.1
  url_launcher: ^6.1.2
  video_player: ^2.4.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
